# Generated by Django 2.2.5 on 2021-05-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=40)),
                ('director', models.CharField(max_length=10)),
                ('keyword', models.CharField(max_length=10)),
            ],
        ),
    ]
