# Generated by Django 3.2.3 on 2021-05-25 02:37

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=40)),
                ('director', models.CharField(max_length=10)),
                ('keyword', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
