# Generated by Django 3.2.3 on 2021-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0003_moviemodel_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='youhoseong', max_length=10)),
                ('keyword', models.CharField(default='', max_length=100)),
                ('movies', models.ManyToManyField(blank=True, related_name='recommend', to='movies.MovieModel')),
            ],
        ),
    ]
