# Generated by Django 3.2.3 on 2021-05-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviemodel_keyword'),
        ('recommends', '0002_rename_movies_recommend_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='movie',
            field=models.ManyToManyField(related_name='recommend', to='movies.MovieModel'),
        ),
    ]
