# Generated by Django 3.1 on 2021-05-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='youhoseong', max_length=10)),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
    ]
