# Generated by Django 3.1 on 2021-05-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluate',
            name='keyword',
            field=models.CharField(default='', max_length=100),
        ),
    ]
