# Generated by Django 3.2.3 on 2021-05-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommend',
            old_name='movies',
            new_name='movie',
        ),
    ]
